export const UPDATE_USER = "UPDATE_USER"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const DELETE_LIST = "DELETE_LIST"
export const TEAM_PAGE = "TEAM_PAGE"
export const UPDATE_BOARD = "UPDATE_BOARD"
export const UPDATE_LISTS = "UPDATE_LISTS"
export const DELETE_TASK = "DELETE_TASK"
